<?php
$strings = array(
         'Inserción realizada con éxito' => 'Inserción realizada con éxito',
        'El usuario ya existe en la base de datos' => 'El usuario ya existe en la base de datos',
	'El empleado ya existe en la base de datos' => 'El empleado ya existe en la base de datos',
        'No se ha podido conectar con la base de datos' => 'No se ha podido conectar con la base de datos',
        'Introduzca un valor para el dni del usuario' => 'Introduzca un valor para el dni del usuario',
	'Introduzca un valor para el dni del empleado' => 'Introduzca un valor para el dni del empleado',
        'Volver' => 'Volver',
        'Error en la consulta sobre la base de datos' => 'Error en la consulta sobre la base de datos',
        'El usuario ha sido borrado correctamente' => 'El usuario ha sido borrado correctamente',
	'El empleado ha sido borrado correctamente' => 'El empleado ha sido borrado correctamente',
        'El usuario no existe' => 'El usuario no existe',
	'El empleado no existe' => 'El empleado no existe',
        'El usuario se ha modificado con éxito' => 'El usuario se ha modificado con éxito',
	'El empleado se ha modificado con éxito' => 'El empleado se ha modificado con éxito',
	'Se ha producido un error en la modificación del usuario' => 'Se ha producido un error en la modificación del usuario',
	'Se ha producido un error en la modificación del empleado' => 'Se ha producido un error en la modificación del empleado',
	'La contraseña para este empleado es erronea'=>'La contraseña para este empleado es erronea',
	'El empleado ya no se encuentra contratado'=>'El empleado ya no se encuentra contratado',
	'Insertar Empleado'=>'Insertar Empleado',
	'Modificar Empleado'=>'Modificar Empleado',
	'USER_DNI' => 'DNI Usuario',
	"La contraseña para este empleado es errónea"=>"La contraseña para este empleado es errónea",
        'USER_FECH_NAC' => 'Fecha Nacimiento Usuario',
        'USER_NOMBRE' => 'Nombre del Usuario',
        'USER_APELLIDO' => 'Apellidos del Usuario',
        'USER_LESIONES' => 'Lesiones del Usuario',
        'USER_PROFESION' => 'Profesión del Usuario',
        'USER_DIRECCION' => 'Dirección del Usuario',
        'USER_EMAIL' => 'Email del Usuario',
	'EMP_TELEFONO'=>'Teléfono',
	'EMP_TELEFONO1'=>'Teléfono 1',
	'EMP_TELEFONO2'=>'Teléfono 2',
	'EMP_TELEFONO3'=>'Teléfono 3',
	'IDIOMA'=>'Idioma',
        'USER_TELEFONO' => 'Teléfono del Usuario',
        'USER_COMENTARIOS' => 'Comentarios',
	'EMP_USER'=>'Usuario',
	'EMP_PASSWORD'=>'Contraseña',
	'EMP_FECH_NAC'=>'Fecha de Nacimiento del Empleado',
	'EMP_EMAIL'=>'Email del Empleado',
	'EMP_NOMBRE'=>'Nombre del Empleado',
	'EMP_APELLIDO'=>'Apellido del Empleado',
	'EMP_DNI'=>'DNI del Empleado',
	'EMP_TELEFONO'=>'Teléfono del Empleado',
	'EMP_CUENTA'=>'Cuenta del Empleado',
	'EMP_DIRECCION'=>'Dirección del Empleado',
	'EMP_COMENTARIOS'=>'Comentarios',
	'EMP_LESIONES'=>'Lesiones',
	'EMP_TIPO'=>'Tipo de Empleado',
	'EMP_ESTADO'=>'Estado del Empleado',
	'EMP_FOTO'=>'Foto de Perfil',
	'EMP_NOMINA'=>'Nómina del Empleado',
	'EMP_USER2'=>'Búsqueda por Usuario:',
	'EMP_DNI2'=>'Búsqueda por DNI:',
	'EMP_NOMBRE2'=>'Búsqueda por Nombre',
	'EMP_APELLIDO2'=>'y Apellido:',
        'Insertar' => 'Insertar',
        'Modificar' => 'Modificar',
        'Borrar' => 'Borrar',
        'Consultar' => 'Consultar',
        'Update' => 'Update',
        'Delete' => 'Delete',
        'Cerrar Sesión' => 'Cerrar Sesión',
	'La pagina ya existe en la base de datos' => 'La página ya existe en la base de datos',
	'Introduzca un valor para la clave de la pagina' => 'Introduzca un valor para la clave de la página',
	'La pagina ha sido borrada correctamente' => 'La página ha sido borrada correctamente',
	'La pagina no existe' => 'La página no existe',
	'La pagina se ha modificado con exito' => 'La página se ha modificado con éxito',
	'Se ha producido un error en la modificacion de la pagina' => 'Se ha producido un error en la modificación de la página',
	'PAGINA_ID' => 'Clave de la página',
	'PAGINA_LINK' => 'Link de la página',
	'PAGINA_NOM' => 'Nombre de la página',
	'Borrar' => 'Borrar',
	'Consultar' => 'Consultar',
	'Listar' => 'Listar',
	'Páginas' => 'Páginas',
	'Paginas' => 'Páginas',
	'(Los campos "Link de la pagina" y "Nombre de la pagina" NO son necesarios)' => '(Los campos "Link de la página" y "Nombre de la página" NO son necesarios)',
	'La funcionalidad ya existe en la base de datos' => 'La funcionalidad ya existe en la base de datos',
	'Introduzca un valor para la clave de la funcionalidad' => 'Introduzca un valor para la clave de la funcionalidad',
	'La funcionalidad ha sido borrada correctamente' => 'La funcionalidad ha sido borrada correctamente',
	'La funcionalidad no existe' => 'La funcionalidad no existe',
	'La funcionalidad se ha modificado con exito' => 'La funcionalidad se ha modificado con áxito',
	'Se ha producido un error en la modificacion de la funcionalidad' => 'Se ha producido un error en la modificación de la funcionalidad',
	'Funcionalidad' => 'Funcionalidad',
	'Funcionalidades' => 'Funcionalidades',
	'(Los campos "Link de la funcionalidad" y "Nombre de la funcionalidad" NO son necesarios)' => '(Los campos "Link de la funcionalidad" y "Nombre de la funcionalidad" NO son necesarios)',
	'Fallo al conectar a MySQL: (' => 'Fallo al conectar a MySQL: (',
	') ' => ') ',
	'Anadida con exito' => 'Añadida con exito',
	'Insertar Rol'=>'Insertar Rol',
	'ROL_ID' => 'ID del Rol',
	'ROL_NOM' => 'Nombre del ROL',
	'GESTION EMPLEADOS'=>'Gestión de empleados',
	'GESTION ROLES'=>'Gestión de roles',
	'GESTION FUNCION'=>'Gestión de funcionalidades',
	'Modificar Rol'=>'Modificar Rol',
	'No funcionalidad'=>'Seleccione alguna funcionalidad',
	'El rol se ha modificado con éxito'=>'El rol se ha modificado con éxito',
	'Borrar Rol'=>'Borrar Rol',
	'El rol ha sido borrado correctamente'=>'El rol ha sido borrado correctamente',
	'El rol no existe'=>'El rol no existe',
	'Páginas' => 'Páginas',
	'Insertar Funcionalidad'=>'Insertar Funcionalidad',
	'FUNCIONALIDAD_ID' => 'ID del la funcionalidad',
	'FUNCIONALIDAD_NOM' => 'Nombre de la funcionalidad',
	'FUNCION_ID' => 'ID del la funcionalidad',
	'FUNCION_NOM' => 'Nombre de la funcionalidad',
	'GESTION EMPLEADOS'=>'Gestión de empleados',
	'GESTION ROLES'=>'Gestión de roles',
	'GESTION FUNCION'=>'Gestión de funcionalidades',
	'Modificar Funcionalidad'=>'Modificar Funcionalidad',
	'No pagina'=>'Seleccione alguna página',
	'La funcionalidad se ha modificado con éxito'=>'La funcionalidad se ha modificado con éxito',
	'Borrar Funcionalidad'=>'Borrar Funcionalidad',
	'La funcionalidad ha sido borrada correctamente'=>'La funcionalidad ha sido borrada correctamente',
	'La funcionalidad no existe'=>'La funcionalidad no existe',
	'Insertar Funcionalidad'=>'Insertar Funcionalidad',
	'Modificar Funcionalidad'=>'Modificar Funcionalidad',
	'Consultar Funcionalidad'=>'Consultar Funcionalidad',
	'Consultar Empleado'=>'Consultar Empleado',
	'Consultar Rol'=>'Consultar Rol',
	'Listar' => 'Listar',
	'Ver' => 'Ver',
	'Pagina' => 'Pagina',
	'Página' => 'Página',
	'Insertar Página'=>'Insertar Página',
	'Anadida con exito'=>'Página añadida con éxito',
	'Modificar Pagina'=>'Modificar Página',
	'La pagina no existe'=>'La página no existe',
	'La pagina se ha modificado con exito'=>'La página se ha modificado con éxito',
	'Borrar Pagina'=>'Borrar Pagina',
	'Borrar Empleado'=>'Borrar Empleado',
	'Borrar Rol'=>'Borrar Rol',
	'Borrar Funcionalidad'=>'Borrar Funcionalidad',
	'Modificar Acciones'=>'Modificar Acciones',
	'No puedes borrar tu propio rol'=>'No puedes borrar tu propio rol',
	'Consultar pagina'=>'Consultar Página',
	'La pagina ha sido borrada correctamente' => 'La pagina ha sido borrada correctamente',
	'La página no existe' => 'La página no existe',
	'La pagina se ha modificado con éxito' => 'La pagina se ha modificado con éxito',
	'Se ha producido un error en la modificación de la pagina' => 'Se ha producido un error en la modificación de la pagina',
	'Introduzca un valor para la clave de la pagina' => 'Introduzca un valor para la clave de la pagina',
	'La pagina ya existe en la base de datos' => 'La pagina ya existe en la base de datos',
	'Gestión de Empleados'=>'Gestión de Empleados',
	'Gestión de Funcionalidades'=>'Gestión de Funcionalidades',
	'Gestión de Roles'=>'Gestión de Roles',
	'Gestión de Páginas'=>'Gestión de Páginas',

	'GESTION EMPLEADOS'=>'GESTIÓN EMPLEADOS',
	'GESTION PAGINAS'=>'GESTIÓN PÁGINAS',
	'GESTION ROLES'=>'GESTIÓN ROLES',
	'GESTION FUNCIONALIDADES'=>'GESTIÓN FUNCIONALIDADES',

	'No tienes los permisos necesarios'=>'No tienes los permisos necesarios',
	'Consulta de Empleados'=>'Consulta de Empleados',
	'Modificar acciones'=>'Acciones',
	'Dni erroneo, la letra del NIF no se corresponde'=>'Dni erroneo, la letra del NIF no se corresponde',
	'Dni erroneo, formato no válido'=>'Dni erroneo, formato no válido',
	'Introduzca un valor para el nombre'=>'Introduzca un valor para el nombre',
	'Introduzca un valor para la contraseña'=>'Introduzca un valor para la contraseña',
	'Introduzca un valor  para la fecha de nacimiento'=>'Introduzca un valor  para la fecha de nacimiento',
	'¿Viene del futuro?'=>'¿Viene del futuro?',
	'Introduzca una dirección de email válida'=>'Introduzca una dirección de email válida',
	'Tiene que escribir un teléfono de 9 dígitos'=>'Tiene que escribir un teléfono de 9 dígitos',
	'Introduzca un valor correcto para el numero de CCC'=>'Introduzca un valor correcto para el numero de CCC',
	'Introduzca dirección'=>'Introduzca dirección',
	'ADMINISTRADOR'=>'ADMINISTRADOR',
	'MONITOR'=>'MONITOR',
	'SECRETARIO'=>'SECRETARIO',
	'Menu Principal'=>'Menú Principal',
	'Centro deportivo'=>'Centro deportivo',
	'Calendario'=>'Calendario',
	'Gestiones Principales'=>'Gestiones Principales',
	'Asistencia Monitores'=>'Asistencia Monitores',
	'Gestiones Secundarias'=>'Gestiones Secundarias',
	'Usuario'=>'Usuario',



    //GESTION DE PAGOS
    'GESTION PAGOS'=>'GESTION PAGOS',

    'Gestión de Pagos'=>'Gestion de Pagos',
    'PAGO_ID'=> 'Identificador del pago',
    'PAGO_FECHA'=>'Fecha de pago',
    'PAGO_CONCEPTO'=>'Concepto',
    'PAGO_IMPORTE'=>'Importe [€]',
    'CLIENTE_ID'=>'Identificador de cliente',
    'Generar Recibo'=>'Generar Recibo',
    'Insertar Pago'=>'Insertar Pago',
    'CLIENTE_DNI'=>'DNI del cliente',
    'Pago registrado correctamente'=>'Pago registrado correctamente',
    'No existe ningún cliente con el DNI introducido'=>'No existe ningún cliente con el DNI introducido',
    'Debe introducir el dni del cliente'=>'Debe introducir el dni del cliente',
    'Debe introducir un importe'=>'Debe introducir un importe',
    'Debe introducir una descripción para el concepto de pago'=>'Debe introducir una descripción para el concepto de pago',
    'Borrar Pago' => 'Borrar Pago',
    'Consultar Pago'=>'Consultar Pago',
    'El pago ha sido borrado correctamente'=>'El pago ha sido borrado correctamente',
    'Modificar Pago' =>'Modificar Pago',
    'El pago se ha modificado correctamente'=>'El pago se ha modificado correctamente',
    'El DNI introducido no pertenece a ningun cliente'=>'El DNI introducido no pertenece a ningun cliente',
    'Se ha generado el recibo de pago'=>'Se ha generado el recibo de pago',
    'PAGO_ESTADO'=>'Estado',
    'Realizar Pago'=> 'Realizar Pago',
    'Ver Recibo'=>'Ver Recibo',
    'PAGO_METODO'=>'Método de Pago',
    'PAGO_DESCUENTO'=>'Descuento [%]',
    'PAGO_IMPORTE_FINAL'=>'Importe Final [€]',




<<<<<<< HEAD
        'DESCUENTO_ID' =>'Clave',
        'DESCUENTO_VALOR'=>'Porcentaje',
        'DESCUENTO_DESCRIPCION'=>'Descripcion',
        'Clave'=>'Clave',
        'Descuento'=>'Porcentaje',
        'Descripcion'=>'Descripcion',
        'Insertar Descuento'=> 'Insertar Descuento',
        'Introduzca un valor entre 0 y 100'=>'Introduzca un valor entre 0 y 100',
        "El descuento no existe" => "El descuento no existe",
        'El descuento ha sido borrado correctamente' => 'El descuento ha sido borrado correctamente',
        'Borrar Descuento' => 'Borrar Descuento',
        'Modificar Descuento'=>'Modificar Descuento',
        "El descuento se ha modificado con éxito"=> "El descuento se ha modificado con éxito",
 "El descuento se ha modificado con éxito"=> "El descuento se ha modificado con éxito",
 
	'La actividad ya existe en la base de datos' => 'La actividad ya existe en la base de datos',
	'Introduzca un valor para la clave de la actividad' => 'Introduzca un valor para la clave de la actividad',
	'La actividad ha sido borrada correctamente' => 'La actividad ha sido borrada correctamente',
	'La actividad no existe' => 'La actividad no existe',
	'La actividad se ha modificado con exito' => 'La actividad se ha modificado con éxito',
	'Se ha producido un error en la modificacion de la actividad' => 'Se ha producido un error en la modificación de la actividad',
	'Añadida con exito' => 'Añadida con exito',

	'Gestión de Actividades' => 'Gestión de Actividades',
	'Consultar pagina' => 'Consultar página',
	'ACTIVIDAD_ID' => 'Identificador Actividad',
	'ACTIVIDAD_NOMBRE'=>'Nombre Actividad',
	'ACTIVIDAD_PRECIO' => 'Precio Actividad',
	'ACTIVIDAD_DESCRIPCION' => 'Descripción actividad', 
	'CATEGORIA_ID' => 'Identificador categoría',
	'Modificar' => 'Modificar',
	'Borrar' => 'Borrar',
	'Insertar Actividad' => 'Insertar Actividad',
	'Modificar Actividad' => 'Modificar Actividad',
	'Borrar Actividad' => 'Borrar Actividad',
	'Insertar' => 'Insertar',
	'Consultar actividad' => 'Consultar actividad',
	'ACTIVO' => 'Activo',
	'CONSULTAR BORRADO' => 'Consultar Inactivas',
	'Consultar' => 'Consultar',
	'CATEGORIA_NOMBRE' => 'Nombre categoría',
	
	
	
=======
    //GESTION DESCUENTOS
    'DESCUENTO_ID' =>'Clave',
    'DESCUENTO_VALOR'=>'Porcentaje',
    'DESCUENTO_DESCRIPCION'=>'Descripcion',
    'Clave'=>'Clave',
    'Descuento'=>'Porcentaje',
    'Descripcion'=>'Descripcion',
    'Insertar Descuento'=> 'Insertar Descuento',
    'Introduzca un valor entre 0 y 100'=>'Introduzca un valor entre 0 y 100',
    "El descuento no existe" => "El descuento no existe",
    'El descuento ha sido borrado correctamente' => 'El descuento ha sido borrado correctamente',
    'Borrar Descuento' => 'Borrar Descuento',
    'Modificar Descuento'=>'Modificar Descuento',
    "El descuento se ha modificado con éxito"=> "El descuento se ha modificado con éxito",
    'Descuentos' => 'Descuentos',
    'Aplicado' => 'Aplicado',
    'Guardar'=> 'Guardar',
    'Asignacion de descuentos correcta'=>'Asignacion de descuentos correcta',

    //GESTION ACTIVIDADES
    'La actividad ya existe en la base de datos' => 'La actividad ya existe en la base de datos',
    'Introduzca un valor para la clave de la actividad' => 'Introduzca un valor para la clave de la actividad',
    'La actividad ha sido borrada correctamente' => 'La actividad ha sido borrada correctamente',
    'La actividad no existe' => 'La actividad no existe',
    'La actividad se ha modificado con exito' => 'La actividad se ha modificado con éxito',
    'Se ha producido un error en la modificacion de la actividad' => 'Se ha producido un error en la modificación de la actividad',
    'Añadida con exito' => 'Añadida con exito',
    'Gestión de Actividades' => 'Gestión de Actividades',
'Gestión de Actividades2' => 'Gestión de Actividades(Con calendario)',
    'Consultar pagina' => 'Consultar página',
    'ACTIVIDAD_ID' => 'Identificador Actividad',
    'ACTIVIDAD_NOMBRE'=>'Nombre Actividad',
    'ACTIVIDAD_PRECIO' => 'Precio Actividad',
    'ACTIVIDAD_DESCRIPCION' => 'Descripción actividad',
    'CATEGORIA_ID' => 'Identificador categoría',
    'Modificar' => 'Modificar',
    'Borrar' => 'Borrar',
    'Insertar Actividad' => 'Insertar Actividad',
    'Modificar Actividad' => 'Modificar Actividad',
    'Borrar Actividad' => 'Borrar Actividad',
    'Insertar' => 'Insertar',
    'Consultar actividad' => 'Consultar actividad',
    'ACTIVO' => 'Activo',
    'CONSULTAR BORRADO' => 'Consultar Inactivas',
    'Consultar' => 'Consultar',
    'LUGAR_NOMBRE' => 'Nombre Lugar',
    'CATEGORIA_NOMBRE' => 'Nombre Categoria',
    
>>>>>>> master
	

    //GESTION LESIONES
    'Lesiones'=>'Lesiones',
    'LESION_ID'=>'ID de la lesión',
    'LESION_NOM'=>'Nombre de la lesión',
    'LESION_DESC'=>'Comentario',
    'LESION_ESTADO'=>'Estado',
    'REGISTRO_CONSULTA_LESION_ID'=> 'ID Registro',
    'REGISTRO_CONSULTA_LESION_FECHAHORA'=> 'Fecha y Hora',
    'REGISTRO_CONSULTA_LESION_FECHAHORA1'=> 'Fecha Inicio',
    'REGISTRO_CONSULTA_LESION_FECHAHORA2'=> 'Fecha Fin',
    'Elige una opcion' => 'Elige una opción',
    'Usuario'=>'Usuario',
    'USUARIO'=>'Realizada por',
    'Consultar Lesion'=>'Buscar lesión',
    'Buscar'=>'Filtrar',
    'Registro'=>'Registro',
    'Consultar Registro'=>'Consultar Registro',
    'Filtrar'=>'Filtrar',
    'Insertar Lesion'=>'Insertar lesión',
    'Modificar lesion'=>'Modificar lesión',
    'Borrar Lesion'=>'Borrar lesión',
    'Lesion modificada correctamente'=>'Lesión modificada correctamente',
    'Lesion borrada correctamente'=>'Lesión borrada correctamente',
    'Lesion registrada correctamente'=>'Lesión registrada correctamente',   
    'Generar'=>'Exportar',
    'Ver'=>'Ver',
    'No existe el registro. Exportelo primero'=>'No existe el registro. Exportelo primero',
   'Registro exportado correctamente'=> 'Registro exportado correctamente',


	'LUGAR_NOMBRE' => 'Nombre Lugar',
	   'CATEGORIA_NOMBRE' => 'Nombre Categoria',




	// GESTION DE CLIENTES
	'CLIENTE_DNI'=>'DNI ',
	'CLIENTE_NOMBRE'=>'Nombre',
	'CLIENTE_APELLIDOS'=>'Apellidos',
	'CLIENTE_FECH_NAC'=>'Fecha de nacimiento',
	'CLIENTE_TELEFONO1'=>'Teléfono 1',
	'CLIENTE_TELEFONO2'=>'Teléfono 2',
	'CLIENTE_TELEFONO3'=>'Teléfono 3',
	'CLIENTE_CORREO'=>'Correo electrónico',
	'CLIENTE_PROFESION'=>'Profesión',
	'CLIENTE_DIRECCION'=>'Dirección',
	'CLIENTE_COMENTARIOS'=>'Comentarios',
	'CLIENTE_DOM'=>'Documento domiciliación',
	'CLIENTE_LOPD'=>'Documento LOPD',
	'CLIENTE_TIPO'=>'Tipo*',
	'Nota'=>'*E=Externo, S=Socio',
	'Insertar Cliente'=>'Insertar Cliente',
	'Modificar Cliente'=>'Modificar Cliente',
	'El cliente se ha modificado con éxito'=>'El cliente se ha modificado con éxito',
	'CLIENTE_ESTADO'=>'Estado',
	'Borrar Cliente'=>'Borrar Cliente',
	'El cliente ha sido borrado correctamente'=>'El cliente ha sido borrado correctamente',
	'Consultar Cliente'=>'Consultar Cliente',
	'CLIENTE_NOMBRE2'=>'Consulta por nombre',
	'CLIENTE_APELLIDOS2'=>'y apellidos:',
	'CLIENTE_DNI2'=>'Consulta por DNI:',
	'El cliente ya existe en la base de datos'=>'El cliente ya existe en la base de datos',
	'Actividades'=>'Actividades',
	'Lesiones'=>'Lesiones',
	'Insertar_Externo'=>'Insertar Externo',
	'InsertarExterno'=>'InsertarExterno',
	'Gestion de Clientes'=>'Gestión de Clientes',
	'HORARIO_RANGO1I'=>'Apertura Lunes:',
	'HORARIO_RANGO1F'=>'Cierre Lunes:',
	'HORARIO_RANGO2I'=>'Apertura Martes:',
	'HORARIO_RANGO2F'=>'Cierre Martes:',
	'HORARIO_RANGO3I'=>'Apertura Miércoles:',
	'HORARIO_RANGO3F'=>'Cierre Miércoles:',
	'HORARIO_RANGO4I'=>'Apertura Jueves:',
	'HORARIO_RANGO4F'=>'Cierre Jueves:',
	'HORARIO_RANGO5I'=>'Apertura Viernes:',
	'HORARIO_RANGO5F'=>'Cierre Viernes:',
	'HORARIO_RANGO6I'=>'Apertura Sábado:',
	'HORARIO_RANGO6F'=>'Cierre Sábado:',



	//HORARIO
	'Gestion de Horario'=>'Gestión de Horario',
	'Lunes'=>'Lunes',
	'Martes'=>'Martes',
	'Miercoles'=>'Miércoles',
	'Jueves'=>'Jueves',
	'Viernes'=>'Viernes',
	'Sabado'=>'Sabado',
	'Insertar Bloque'=>'Insertar Hora Posible',
	'BLOQUE_ID'=>'ID',
	'BLOQUE_FECHA'=>'Fecha',
	'BLOQUE_DIA'=>'Día',
	'BLOQUE_HORAI'=>'Hora Inicio',
	'BLOQUE_HORAF'=>'Hora Fin',
	'BLOQUE_LUGAR'=>'Lugar',
	'Borrar Bloque'=>'Borrar Hora Posible',
	'El BLOQUE no existe'=>'El bloque no existe',
	'El BLOQUE ha sido borrado correctamente'=>'El bloque ha sido borrado correctamente',
	'Modificar Bloque'=>'Modificar Bloque',
	'El BLOQUE se ha modificado con éxito'=>'El bloque se ha modificado con éxito',
	'Consultar Bloque'=>'Consultar Bloque',
	'El BLOQUE ya está ocupado'=>'El bloque ya está ocupado',
	'BLOQUE_ACT1'=>'Actividad 1',
	'BLOQUE_ACT2'=>'Actividad 2',
	'BLOQUE_ACT3'=>'Actividad 3',
	'BLOQUE_EV1'=>'Evento 1',
	'BLOQUE_EV2'=>'Evento 2',
	'BLOQUE_EV3'=>'Evento 3',
	'ActEv'=>'Actividades/Eventos actuales',
	'ACTIVIDADES'=>'ACTIVIDADES',
	'EVENTOS'=>'EVENTOS',
	'clase'=>'clase',
	'profesores'=>'PROFESORES',
	'alumnos'=>'ALUMNOS:',
	//gestion horario

	'Insertar Horario'=>'Insertar Horario',
	'HORARIO_NOMBRE'=>'Nombre',
	'HORARIO_FECHAI'=>'Fecha Inicial',
	'HORARIO_FECHAF'=>'Fecha Final',
	'HORARIO_ID'=>'HORARIO_ID',
	'Modificar Rol'=>'Modificar Rol',
	'Modificar Horario'=>'Modificar Horario',
	'El HORARIO se ha modificado con éxito'=>'El horario se ha modificado con éxito',
	'Borrar Horario'=>'Borrar Horario',
	'El HORARIO ha sido borrado correctamente'=>'El HORARIO ha sido borrado correctamente',
	'Consultar Horario'=>'Consultar Horario',
	'Domingo'=>'Domingo',
	'BLOQUE_HORARIO'=>'Horario',
	'PROFESORES'=>'PROFESORES:',
	'ACTIVIDAD_DIA'=>'Día de la semana',
	'ACTIVIDAD_HORARIO'=>'Horario',
	'CATEGORIA_NOMBRE'=>'Nombre de la categoria',
	'Continuar'=>'Continuar',
	'profesor'=>'profesor',
	'LUGARES'=>'LUGARES:',
	'ACTIVIDAD_BLOQUE'=>'Seleccione horas posibles:',
	'No hay bloques definidos para ese día en ese horario'=>'No hay bloques definidos para ese día en ese horario',
	'Continuar'=>'Continuar',
	'Gestion de Posibles'=>'Gestión de horas posibles',
	

    

    //ENVIO NOTIFICACIONES ->EMPLEADOS/CLIENTES
    'Enviar Notificacion'=>'Enviar Notificación',
    'ENVIAR NOTIFICACION'=>'Enviar Notificación',
    'Clientes'=>'Siguiente',
    'Empleados'=>'Continuar',
    'Notificacion sobre Clientes'=>'Notificación sobre Clientes',
    'Notificacion sobre Empleados'=>'Notificación sobre Empleados',
    'Actividades'=>'Actividad',
    'SELECT'=>'Selección',
    'Seleccionar'=>'Seleccionar',
    'email'=>'email',
    'DEST'=>'Destinatarios',
    'NOTIFICACION_REMITENTE'=>'Dirección GMAIL del remitente',
    'NOTIFICACION_PASSWORD'=>'Contraseña GMAIL del remitente',
    'NOTIFICACION_NOMBRE_REMITENTE'=>'Nombre completo',
    'NOTIFICACION_ASUNTO'=>'Asunto',
    'NOTIFICACION_CUERPO'=>'Cuerpo',
    'NOTIFICACION_FECHAHORA'=>'Fecha y Hora',
    'NOTIFICACION_FECHAHORA1'=>'Fecha Inicio',
    'NOTIFICACION_FECHAHORA2'=>'Fecha Fin',
    'NOTIFICACION_DESTINATARIO'=>'Destinatario',
    'Consultar Notificacion'=>'Filtrar Notificación',
    'Mensaje'=>'Mensaje',
    'Redactar Email'=>'Redactar Email',
    'Enviar'=>'Enviar',
    'Notificacion enviada con exito'=>'Notificacion enviada con éxito',
    'Ha ocurrido un error durante el envio de las notificaciones'=>'Ha ocurrido un error durante el envío de las notificaciones',

    //ENVIO NOTIFICACIONES -> ACTIVIDADES
    'Actividad'=>'Confirmar',
    'Notificacion sobre Actividades'=>'Notificación sobre Actividades',
    'ACTIVIDAD_ID'=>'ACTIVIDAD_ID',
    'ACTIVIDAD_NOMBRE'=>'Nombre Actividad',
    'Seleccionar'=>'Seleccionar',
    'actividad'=>'Actividad',
    'Actividad_Monitor'=>'Seguir',
    



    //ENVIO NOTIFICACIONES ->EVENTOS
    'Eventos'=>'Evento',
    'Evento'=>'Seleccionar',
    'Notificacion sobre Eventos'=>'Notificación sobre Eventos',
    'EVENTO_ID'=>'ID Evento',
    'EVENTO_NOMBRE'=>'Nombre',
    'EVENTO_ORGANIZADOR'=>'Organizador',
    'EVENTO_DESCRIPCION'=>'Descripción'




)
?>
