<?php
$stringsCF = array(
'No se ha podido conectar con la base de datos' => 'Could not connect to the database',
'Volver' => 'Return',
'Error en la consulta sobre la base de datos' => 'Could not connect to the database',
'Insertar' => 'Insert',
'Modificar' => 'Modify',
'Borrar' => 'Delete',
'Consultar' => 'Consult',
'Update' => 'Update',
'Delete' => 'Delete',
'Cerrar Sesión' => 'Sign off',
'Listar' => 'List',
'Fallo al conectar a MySQL: (' => 'Could not connect to MySQL: (',
') ' => ') ',
'Anadida con exito' => 'Added successfully',	
'Ver' => 'Show',		
'No tienes los permisos necesarios'=>'You do not have permission',
'Menu Principal'=>'Main Menu',
'Centro deportivo'=>'Sports Center',
'Calendario'=>'Calendar',
'Gestiones Principales'=>'Main options',
'Asistencia Monitores'=>'Instructors Assistance',
'Gestiones Secundarias'=>'Secondary options',
'Usuario'=>'User',

'La caja se ha modificado con exito' => 'The box has been modified succesfully',
'La caja no existe' => 'The box doesnt exist',
'Los ingresos se han añadido con éxito'=> 'Revenue has been added succesfully',
'CAJA_INGRESOS' => 'Income',
'Añadir Ingresos Extra' => 'Add Extra Income',
'CAJA_INGRESAR' => 'Introduce income´s value',
'Listar Cajas' => 'Box List',
'CAJA_FECHA' => 'Date',
'Hacer Caja' => 'Make Box',

'FACTURA_ID' => 'Bill´s number',
'FACTURA_FECHA' => 'Date',
'CLIENTE_ID' => 'Customer´s ID',
'CLIENTE_NOMBRE' => 'Name',
'CLIENTE_APELLIDOS' => 'Surname (Optional)',
'CLIENTE_NIF' => 'NIF/VAF',
'LINEA_FACTURA_ID' => 'Line number',
'LINEA_FACTURA_UNIDADES' => 'Units',
'LINEA_FACTURA_CONCEPTO' => 'Concept',
'LINEA_FACTURA_PRECIOUD' => 'Unit Price',
'La factura se ha modificado con exito' => 'The bill modified succesfully',
'La factura no existe' => 'The bill doesn´t exist',
'La linea de factura se ha modificado con exito' => 'The bill´s line has been modified succesfully',
'La linea de factura no existe' => 'The bill´s line has been modified succesfully',
'Gestion de Facturas' => 'Bills Managemente',
'Modificar Lineas Factura' => 'Modify bill´s line',
'Insertar Lineas Factura' => 'Add bill´s line',
'Crear Factura' => 'Make bill',
'Modificar Factura' => 'Modify bill',
'Eliminar Factura' => 'Remove bill',
'Consultar/Imprimir' => 'Show/Print',
'Parar' => 'Stop',
'La factura ha sido borrada correctamente' => 'The bill has been removed succesfully',
'Lineas Factura' => 'Bill´s line'

)
?>
