<?php
$strings = array(
'Inserción realizada con éxito' => 'Successful insertion',
'El usuario ya existe en la base de datos' => 'User already exists',
	'El empleado ya existe en la base de datos' => 'Employee already exists',
'No se ha podido conectar con la base de datos' => 'Could not connect to the database',
'Introduzca un valor para el dni del usuario' => 'Enter a value for DNI',
	'Introduzca un valor para el dni del empleado' => 'Enter a value for DNI',
'Volver' => 'Return',
'Error en la consulta sobre la base de datos' => 'Could not connect to the database',
'El usuario ha sido borrado correctamente' => 'User deleted successfully',
	'El empleado ha sido borrado correctamente' => 'Employee deleted successfully',
'El usuario no existe' => 'User do not exists',
	'El empleado no existe' => 'Employee do not exists',
'El usuario se ha modificado con éxito' => 'User modified successfully',
	'El empleado se ha modificado con éxito' => 'Employee modified successfully',

	'Se ha producido un error en la modificación del usuario' => 'Could not connect modify user',
	'Se ha producido un error en la modificación del empleado' => 'Could not connect modify employee',

	'La contraseña para este empleado es erronea'=>'Wrong password',
	'El empleado ya no se encuentra contratado'=>'Employee is already hired',
	'Insertar Empleado'=>'Insert Employee',
	'Modificar Empleado'=>'Modify Employee',
	'USER_DNI' => 'User DNI',
	"La contraseña para este empleado es errónea"=>"Wrong password",

'USER_FECH_NAC' => 'Birth date',
'USER_NOMBRE' => 'Name',
'USER_APELLIDO' => 'Surname',
'USER_LESIONES' => 'Injuries',
'USER_PROFESION' => 'Profession',
'USER_DIRECCION' => 'Adress',
'USER_EMAIL' => 'Email',
	'EMP_TELEFONO'=>'Telphone Number',

	'IDIOMA'=>'Language',

    'USER_TELEFONO' => 'Telephone Number',
    'USER_COMENTARIOS' => 'Comsents',

	'EMP_USER'=>'User',
	'EMP_PASSWORD'=>'Password',
	'EMP_FECH_NAC'=>'Birth date',
	'EMP_EMAIL'=>'Email',
	'EMP_NOMBRE'=>'Name',
	'EMP_APELLIDO'=>'Surname',
	'EMP_DNI'=>'DNI',
	'EMP_TELEFONO'=>'Telephone Number',
	'EMP_CUENTA'=>'Account Number',
	'EMP_DIRECCION'=>'Adress',
	'EMP_COMENTARIOS'=>'Comments',
	'EMP_LESIONES'=>'Injuries',
	'EMP_TIPO'=>'Type',
	'EMP_ESTADO'=>'Status',
	'EMP_FOTO'=>'Profile Photo',
	'EMP_NOMINA'=>'Paysheet',
	'EMP_USER2'=>'Search by User:',
	'EMP_DNI2'=>'Search by DNI:',
	'EMP_NOMBRE2'=>'Search by Name',
	'EMP_APELLIDO2'=>'and Surname:',

'Insertar' => 'Insert',
'Modificar' => 'Modify',
'Borrar' => 'Delete',
'Consultar' => 'Consult',
'Update' => 'Update',
'Delete' => 'Delete',
'Cerrar Sesión' => 'Sign off',

	'La pagina ya existe en la base de datos' => 'Page already exists',

	'La pagina ha sido borrada correctamente' => 'Page deleted successfully',
	'La pagina no existe' => 'Page do not exists',
	'La pagina se ha modificado con exito' => 'Page modified successfully',
	'Se ha producido un error en la modificacion de la pagina' => 'Could not modify page',
	'PAGINA_ID' => 'Page Key',
	'PAGINA_LINK' => 'Page Link',
	'PAGINA_NOM' => 'Page Name',
	'Borrar' => 'Delete',
	'Consultar' => 'Consult',
	'Listar' => 'List',
	'Páginas' => 'Pages',
	'Paginas' => 'PAges',


	'La funcionalidad ya existe en la base de datos' => 'Functionality already exists',

	'La funcionalidad ha sido borrada correctamente' => 'Functionality deleted successfully',
	'La funcionalidad no existe' => 'Functionality do not exists',
	'La funcionalidad se ha modificado con exito' => 'Functionality successfully modified',
	'Se ha producido un error en la modificacion de la funcionalidad' => 'Could not modify functionality',

	'Funcionalidad' => 'Functionality',
	'Funcionalidades' => 'Functionalities',


	'Fallo al conectar a MySQL: (' => 'Could not connect to MySQL: (',
	') ' => ') ',
	'Anadida con exito' => 'Added successfully',
	'Insertar Rol'=>'Insert Role',
	'ROL_ID' => 'Role ID',
	'ROL_NOM' => 'Role Name',
	'GESTION EMPLEADOS'=>'Employees management',
	'GESTION ROLES'=>'Roles management',
	'GESTION FUNCION'=>'Functionalities management',
	'Modificar Rol'=>'Modify Role',
	'No funcionalidad'=>'Select at least one functionality',
	'El rol se ha modificado con éxito'=>'Role modified successfully',
	'Borrar Rol'=>'Delete Role',
	'El rol ha sido borrado correctamente'=>'Role deleted successfully',
	'El rol no existe'=>'Role do not exists',
	'Páginas' => 'Pages',

	'Insertar Funcionalidad'=>'Insert Functionality',
	'FUNCIONALIDAD_ID' => 'Functionality ID',
	'FUNCIONALIDAD_NOM' => 'Functionality Name',
	'FUNCION_ID' => 'Functionality ID',

	'GESTION EMPLEADOS'=>'Employees Management',
	'GESTION ROLES'=>'Roles Management',
	'GESTION FUNCION'=>'Functionalities Management',
	'Modificar Funcionalidad'=>'Modify Functionality',
	'No pagina'=>'Select at least one page',
	'La funcionalidad se ha modificado con éxito'=>'Functionality modified successfully',
	'Borrar Funcionalidad'=>'Delete Functionality',
	'La funcionalidad ha sido borrada correctamente'=>'Functionality deleted successfully',
	'La funcionalidad no existe'=>'Functionality do not exists',
	'Insertar Funcionalidad'=>'Insert Functionality',
	'Modificar Funcionalidad'=>'Modify Functionality',
	'No puedes borrar tu propio rol'=>'Cannot delete your own role',
	'Consultar Funcionalidad'=>'Consult Functionality',
	'Consultar Empleado'=>'Consult Employee',
	'Consultar Rol'=>'Consult Role',
	'Listar' => 'List',
	'Ver' => 'Show',
	'Pagina' => 'Page',
	'Página' => 'Page',
	'Insertar Página'=>'Insert Páge',
	'Anadida con exito'=>'Added succesfully',
	'Modificar Pagina'=>'Modify Page',
	'La pagina no existe'=>'Page do not exists',
	'La pagina se ha modificado con exito'=>'Page modified successfully',
	'Borrar Pagina'=>'Delete Page',
	'Borrar Empleado'=>'Delete Employee',
	'Borrar Rol'=>'Delete Role',
	'Borrar Funcionalidad'=>'Delete Funcionality',
	'Modificar Acciones'=>'Modify Actions',
	'Consultar pagina'=>'Consult Page',
	'La pagina ha sido borrada correctamente' => 'Page successfully deleted',
	'La página no existe' => 'Page do not exists',
	'La pagina se ha modificado con éxito' => 'Page successfully modified',
	'Se ha producido un error en la modificación de la pagina' => 'Could not modify page',

	'La pagina ya existe en la base de datos' => 'Page already exists',
	'Gestión de Empleados'=>'Employees Management',
	'Gestión de Funcionalidades'=>'Functionalities Management',
	'Gestión de Roles'=>'Roles Management',
	'Gestión de Páginas'=>'Pages Management',
  	'GESTION EMPLEADOS'=>'Employees Management',
	'GESTION PAGINAS'=>'Pages Management',
	'GESTION ROLES'=>'Roles Management',
	'GESTION FUNCIONALIDADES'=>'Functionalities Management',
   
	'No tienes los permisos necesarios'=>'You do not have permission',
	'Consulta de Empleados'=>'Employee Consultation',
	'Modificar acciones'=>'Actions',
	'Dni erroneo, la letra del NIF no se corresponde'=>'Wrong ID letter',
	'Dni erroneo, formato no válido'=>'Wrong ID format',
	'Introduzca un valor para el nombre'=>'Enter a valid name',
	'Introduzca un valor para la contraseña'=>'Enter a valid password',
	'Introduzca un valor  para la fecha de nacimiento'=>'Enter a birth date',
	'¿Viene del futuro?'=>'¿Is he from the future?',
	'Introduzca una dirección de email válida'=>'Enter a valid email address',
	'Tiene que escribir un teléfono de 9 dígitos'=>'Enter a valid telephone number',
	'Introduzca un valor correcto para el numero de CCC'=>'Enter a valid CCC account number',
	'Introduzca dirección'=>'Enter address',
	'ADMINISTRADOR'=>'ADMINISTRATOR',
	'MONITOR'=>'INSTRUCTOR',
	'SECRETARIO'=>'SECRETARY',
	'Menu Principal'=>'Main Menu',
	'Centro deportivo'=>'Sports Center',
	'Calendario'=>'Calendar',
	'Gestiones Principales'=>'Main options',
	'Asistencia Monitores'=>'Instructors Assistance',
	'Gestiones Secundarias'=>'Secondary options',
	'Usuario'=>'User',

 'GESTION PAGOS'=>'Payments Management',
  'Gestión de Pagos'=>'Payments Management',
    'PAGO_ID'=>'Payment ID',
    'PAGO_FECHA'=>'Payment Data',
    'PAGO_CONCEPTO'=>'Concept',
    'PAGO_IMPORTE'=>'Amount',
    'CLIENTE_ID'=>'Client ID',
'Generar Recibo'=>'Generate Receip',
    'Insertar Pago'=>'Insert Payment',
'CLIENTE_DNI'=>'Customer DNI',
'Pago registrado correctamente'=>'Payment Succesfully Registered',
    'No existe ningún cliente con el DNI introducido'=>'There is no customer with the DNI entered',
    'Debe introducir el dni del cliente'=>'You must enter the customer DNI ',
    'Debe introducir un importe'=>'You must enter an amount',
    'Debe introducir una descripción para el concepto de pago'=>'You must enter a description for the concept of payment',
    'Borrar Pago' => 'Delete Payment',
    'Consultar Pago'=> 'Payment Consultation',
    'El pago ha sido borrado correctamente'=>'The payment has been erased successfully',
    'Modificar Pago' => 'Edit Payment',
    'El pago se ha modificado correctamente'=>'The payment has been edited successfully',
    'El DNI introducido no pertenece a ningun cliente'=>"Introduced DNI doesn't belong to any client"
)
?>
