<?php
$strings = array(
'Inserción realizada con éxito' => 'Inserción realizada con éxito',
'El usuario ya existe en la base de datos' => 'O usuario xa existe na base de datos',
	'El empleado ya existe en la base de datos' => 'O empregado xa existe na base de datos',
'No se ha podido conectar con la base de datos' => 'Non se puido conectar coa base de datos',
'Introduzca un valor para el dni del usuario' => 'Introduza un valor o dni do usuario',
	'Introduzca un valor para el dni del empleado' => 'Introduza un valor para o dni do empregado',
'Volver' => 'Volver',
'Error en la consulta sobre la base de datos' => 'Erro na consulta sobre base de datos',
'El usuario ha sido borrado correctamente' => 'O usuario borrouse corectamente',
	'El empleado ha sido borrado correctamente' => 'O empregado borrouse correctamente',
'El usuario no existe' => 'O usuario non existe',
	'El empleado no existe' => 'O empregado non existe',
'El usuario se ha modificado con éxito' => 'O usuario modificouse con éxito',
	'El empleado se ha modificado con éxito' => 'O empregado modificouse con éxito',
	'La contraseña para este empleado es erronea'=>'O contrasinal para este empregado é erróneo',
	'El empleado ya no se encuentra contratado'=>'O empregado xa non está contratado',

	'Se ha producido un error en la modificación del usuario' => 'Produciuse un erro na modificación do usuario',
	'Se ha producido un error en la modificación del empleado' => 'Produciuse un erro na modificación do empregado',
'USER_DNI' => 'DNI Usuario',

'USER_FECH_NAC' => 'Data Nacemento Usuario',
'USER_NOMBRE' => 'Nome do Usuario',
'USER_APELLIDO' => 'Apelidos do Usuario',
'USER_LESIONES' => 'Lesións do Usuario',
'USER_PROFESION' => 'Profesión do Usuario',
'USER_DIRECCION' => 'Dirección do Usuario',
'USER_EMAIL' => 'Email do Usuario',
	'IDIOMA'=>'Idioma',

    'USER_TELEFONO' => 'Teléfono do Usuario',
    'USER_COMENTARIOS' => 'Comentarios',
	'EMP_TELEFONO'=>'Teléfono',

	'EMP_USER'=>'Usuario',
	'EMP_PASSWORD'=>'Contrasinal',
	'EMP_FECH_NAC'=>'Fecha de Nacemento do empregado',
	'EMP_EMAIL'=>'Email do empregado',
	'EMP_NOMBRE'=>'Nome do empregado',
	'EMP_APELLIDO'=>'Apelido do empregado',
	'EMP_DNI'=>'DNI do empregado',
	'EMP_TELEFONO'=>'Teléfono do empregado',
	'EMP_CUENTA'=>'Conta do empregado',
	'EMP_DIRECCION'=>'Direción do empregado',
	'EMP_COMENTARIOS'=>'Comentarios',
	'EMP_LESIONES'=>'Lesións',
	'EMP_TIPO'=>'Tipo de empregado',
	'EMP_ESTADO'=>'Estado do empregado',
	'EMP_FOTO'=>'Foto de Perfil',
	'EMP_NOMINA'=>'Nómina do empregado',
	'EMP_USER2'=>'Búsqueda por Usuario:',
	'EMP_DNI2'=>'Búsqueda por DNI',
	'EMP_NOMBRE2'=>'Búsqueda por Nome',
	'EMP_APELLIDO2'=>'e Apelido',
	'Insertar Empleado'=>'Inserir Empregado',
	'Modificar Empleado'=>'Modificar Empregado',
	"La contraseña para este empleado es errónea"=>"O contrasinal para o empregado é erróneo",

'Insertar' => 'Inserir',
'Modificar' => 'Modificar',
'Borrar' => 'Borrar',
'Consultar' => 'Consultar',
'Update' => 'Update',
'Delete' => 'Delete',
'Cerrar Sesión' => 'Cerrar Sesión',

'La pagina ya existe en la base de datos' => 'A páxina xa existe na base de datos',
'Introduzca un valor para la clave de la pagina' => 'Introduzca un valor para a clave da páxina',
'La pagina ha sido borrada correctamente' => 'A páxina borrouse correctamente',
'La pagina no existe' => 'A páxina non existe',
'La pagina se ha modificado con exito' => 'A páxina modificouse con éxito',
'Se ha producido un error en la modificación de la pagina' => 'Produciuse un erro na modificación da páxina',
'PAGINA_ID' => 'Clave da páxina',
'PAGINA_LINK' => 'Link da páxina',
'PAGINA_NOM' => 'Nome da páxina',
'Borrar' => 'Borrar',
'Consultar' => 'Consultar',
'Listar' => 'Listar',
'Pagina' => 'Páxina',
'Paginas' => 'Páxinas',
	
'La funcionalidad ya existe en la base de datos' => 'A funcionalidade xa existe na base de datos',
'Introduzca un valor para la clave de la funcionalidad' => 'Introduzca un valor para a clave da funcionalidade',
'La funcionalidad ha sido borrada correctamente' => 'A funcionalidade borrouse correctamente',
'La funcionalidad no existe' => 'A funcionalidade non existe',
'La funcionalidad se ha modificado con exito' => 'A funcionalidade modificouse con éxito',
'Se ha producido un error en la modificacion de la funcionalidad' => 'Produciuse un erro na modificación da funcionalidade',
'FUNCIONALIDAD_ID' => 'Clave da funcionalidade',
'FUNCIONALIDAD_LINK' => 'Link da funcionalidade',
'Funcionalidad' => 'Funcionalidade',
'Funcionalidades' => 'Funcionalidades'
)
?>
