<?php
$strings = array(
'Inserción realizada con éxito' => 'Inserción realizada con éxito',
'El usuario ya existe en la base de datos' => 'El usuario ya existe en la base de datos',
	'El empleado ya existe en la base de datos' => 'El empleado ya existe en la base de datos',
'No se ha podido conectar con la base de datos' => 'No se ha podido conectar con la base de datos',
'Introduzca un valor para el dni del usuario' => 'Introduzca un valor para el dni del usuario',
	'Introduzca un valor para el dni del empleado' => 'Introduzca un valor para el dni del empleado',
'Volver' => 'Volver',
'Error en la consulta sobre la base de datos' => 'Error en la consulta sobre la base de datos',
'El usuario ha sido borrado correctamente' => 'El usuario ha sido borrado correctamente',
	'El empleado ha sido borrado correctamente' => 'El empleado ha sido borrado correctamente',
'El usuario no existe' => 'El usuario no existe',
	'El empleado no existe' => 'El empleado no existe',
'El usuario se ha modificado con éxito' => 'El usuario se ha modificado con éxito',
	'El empleado se ha modificado con éxito' => 'El empleado se ha modificado con éxito',

	'Se ha producido un error en la modificación del usuario' => 'Se ha producido un error en la modificación del usuario',
	'Se ha producido un error en la modificación del empleado' => 'Se ha producido un error en la modificación del empleado',

	'La contraseña para este empleado es erronea'=>'La contraseña para este empleado es erronea',
	'El empleado ya no se encuentra contratado'=>'El empleado ya no se encuentra contratado',
	'Insertar Empleado'=>'Insertar Empleado',
	'Modificar Empleado'=>'Modificar Empleado',
	'USER_DNI' => 'DNI Usuario',
	"La contraseña para este empleado es errónea"=>"La contraseña para este empleado es errónea",

'USER_FECH_NAC' => 'Fecha Nacimiento Usuario',
'USER_NOMBRE' => 'Nombre del Usuario',
'USER_APELLIDO' => 'Apellidos del Usuario',
'USER_LESIONES' => 'Lesiones del Usuario',
'USER_PROFESION' => 'Profesión del Usuario',
'USER_DIRECCION' => 'Dirección del Usuario',
'USER_EMAIL' => 'Email del Usuario',
	'EMP_TELEFONO'=>'Teléfono',
	'EMP_TELEFONO1'=>'Teléfono 1',
	'EMP_TELEFONO2'=>'Teléfono 2',
	'EMP_TELEFONO3'=>'Teléfono 3',
	'IDIOMA'=>'Idioma',



    'USER_TELEFONO' => 'Teléfono del Usuario',
    'USER_COMENTARIOS' => 'Comentarios',

	'EMP_USER'=>'Usuario',
	'EMP_PASSWORD'=>'Contraseña',
	'EMP_FECH_NAC'=>'Fecha de Nacimiento del Empleado',
	'EMP_EMAIL'=>'Email del Empleado',
	'EMP_NOMBRE'=>'Nombre del Empleado',
	'EMP_APELLIDO'=>'Apellido del Empleado',
	'EMP_DNI'=>'DNI del Empleado',
	'EMP_TELEFONO'=>'Teléfono del Empleado',
	'EMP_CUENTA'=>'Cuenta del Empleado',
	'EMP_DIRECCION'=>'Dirección del Empleado',
	'EMP_COMENTARIOS'=>'Comentarios',
	'EMP_LESIONES'=>'Lesiones',
	'EMP_TIPO'=>'Tipo de Empleado',
	'EMP_ESTADO'=>'Estado del Empleado',
	'EMP_FOTO'=>'Foto de Perfil',
	'EMP_NOMINA'=>'Nómina del Empleado',
	'EMP_USER2'=>'Búsqueda por Usuario:',
	'EMP_DNI2'=>'Búsqueda por DNI',
	'EMP_NOMBRE2'=>'Búsqueda por Nombre',
	'EMP_APELLIDO2'=>'y Apellido',

'Insertar' => 'Insertar',
'Modificar' => 'Modificar',
'Borrar' => 'Borrar',
'Consultar' => 'Consultar',
'Update' => 'Update',
'Delete' => 'Delete',
'Cerrar Sesión' => 'Cerrar Sesión',
	
'La pagina ya existe en la base de datos' => 'La pagina ya existe en la base de datos',
'Introduzca un valor para la clave de la pagina' => 'Introduzca un valor para la clave de la pagina',
'La pagina ha sido borrada correctamente' => 'La pagina ha sido borrada correctamente',
'La pagina no existe' => 'La pagina no existe',
'La pagina se ha modificado con éxito' => 'La pagina se ha modificado con éxito',
'Se ha producido un error en la modificación de la pagina' => 'Se ha producido un error en la modificación de la pagina',
'PAGINA_ID' => 'Clave de la pagina',
'PAGINA_LINK' => 'Link de la pagina',
'PAGINA_NOM' => 'Nombre de la pagina',
'Borrar' => 'Borrar',
'Consultar' => 'Consultar',
'Listar' => 'Listar'
)
?>
