CREATE TABLE EMPLEADOS
(
    EMP_USER VARCHAR(25) PRIMARY KEY NOT NULL,
    EMP_PASSWORD VARCHAR(128) NOT NULL,
    EMP_NOMBRE VARCHAR(25) NOT NULL,
    EMP_APELLIDO VARCHAR(50) NOT NULL,
    EMP_DNI VARCHAR(10) NOT NULL,
    EMP_FECH_NAC DATE NOT NULL,
    EMP_EMAIL VARCHAR(50) NOT NULL,
    EMP_TELEFONO INT(15),
    EMP_CUENTA VARCHAR(60) NOT NULL,
    EMP_DIRECCION VARCHAR(80) NOT NULL,
    EMP_COMENTARIOS VARCHAR(1000),
    EMP_TIPO ENUM('ADMIN', 'SECRETARIO', 'MONITOR CONTRATADO', 'MONITOR INVITADO') NOT NULL,
    EMP_ESTADO ENUM('Activo', 'Inactivo') NOT NULL,
    EMP_FOTO VARCHAR(500),
    EMP_NOMINA VARCHAR(500)
);
CREATE INDEX EMP_USER ON EMPLEADOS (EMP_USER);

INSERT INTO EMPLEADOS (EMP_USER, EMP_PASSWORD, EMP_NOMBRE, EMP_APELLIDO, EMP_DNI, EMP_FECH_NAC, EMP_EMAIL, EMP_TELEFONO, EMP_CUENTA, EMP_DIRECCION, EMP_COMENTARIOS, EMP_TIPO, EMP_ESTADO, EMP_FOTO, EMP_NOMINA) VALUES ('ADMIN','ADMIN','','','',0000-00-00,'',0,'','','','ADMIN','Activo','','');

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `FUNCIONALIDAD` (
`FUNCIONALIDAD_ID` int(10) NOT NULL,
  `FUNCIONALIDAD_NOM` varchar(20) CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `FUNCIONALIDAD`
 ADD PRIMARY KEY (`FUNCIONALIDAD_ID`);
 
 ALTER TABLE `FUNCIONALIDAD`
MODIFY `FUNCIONALIDAD_ID` int(10) NOT NULL AUTO_INCREMENT;

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `PAGINA` (
`PAGINA_ID` int(10) NOT NULL,
  `PAGINA_LINK` varchar(50) COLLATE latin1_spanish_ci NOT NULL,
  `PAGINA_NOM` varchar(20) COLLATE latin1_spanish_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

ALTER TABLE `PAGINA`
 ADD PRIMARY KEY (`PAGINA_ID`);
 
 ALTER TABLE `PAGINA`
MODIFY `PAGINA_ID` int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;

-- --------------------------------------------------------
